#ifndef MEMORY_CONSTS_H
#define MEMORY_CONSTS_H

#define NUMBER_OF_PAGE_DIRECTORIES 1
#define TABLES_PER_DIRECTORY 256        // 256MB
#define PAGE_SIZE 1024                  // 4KB
#define PAGES_PER_TABLE 1024

#define NUMBER_OF_INITIAL_TABLES 4
#endif